# Generated by Django 2.2.16 on 2022-11-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20221125_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Картинки', 'verbose_name_plural': 'Картинки'},
        ),
    ]
